name: Run tests and publish Allure report to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Repository'yi checkout et
      - name: Checkout code
        uses: actions/checkout@v3

      # JDK kurulumu
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Maven ile testleri çalıştır
      - name: Run tests
        run: mvn clean test

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
         ref: gh-pages
         path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        #id: allure-report
        with:
          gh_pages: gh-pages
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history