name: Run tests and upload Allure single-file report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Repository'yi checkout et
      - uses: actions/checkout@v3

      # Maven için JDK ayarı
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Testleri çalıştır
      - name: Run tests
        run: mvn clean test

      # Allure raporunu tek dosya olarak oluştur
      - name: Allure Single File Report
        uses: jcleigh/allure-single-file-report-action@v1.0.0
        with:
          allure_results: target/allure-results
          allure_report: target/allure-report.html

      # Raporu GitHub Artifacts olarak yükle
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/allure-report.html
