name: Run tests and publish Allure report to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # gh-pages branch'ını da checkout et
      - name: Checkout code and gh-pages
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Tüm geçmişi indir
          ref: gh-pages
          path: gh-pages

      # Ana branch'ı checkout et
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main

      # JDK kurulumu
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Dizin içeriğini değiştir
      - name: Prepare working directory
        run: |
          cd main
          mvn clean test

      # Allure raporunu GitHub Pages'de yayınlamak için yükle
      - name: Publish Allure Report
        uses: simple-elf/allure-report-action@v1.11
        if: always()
        with:
          allure_results: main/target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      # GitHub Pages'e yükle
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report