name: Run tests and upload Allure report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Repository'yi checkout et
      - uses: actions/checkout@v3

      # Maven için JDK ayarı
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Testleri çalıştır
      - name: Run tests
        run: mvn clean test

      - name: Check Test Results
        run: ls -R target/allure-results/

      # Allure Commandline Tool'u indir ve kur
      - name: Install Allure Commandline
        run: |
          wget -qO- https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.tgz | tar -xz
          sudo mv allure-2.20.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # Allure raporunu oluştur
      - name: Generate Allure Report
        run: allure generate target/allure-results -o target/allure-report

      # Allure raporunu yükle
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/
