name: Run tests and upload Allure report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Repository'yi checkout et
      - uses: actions/checkout@v3

      # Maven için JDK ayarı
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Testleri çalıştır
      - name: Run tests
        run: mvn clean test

      # Test sonuçlarını kontrol et
      - name: Check Test Results
        run: ls -R target/allure-results/

      # Allure raporunu oluştur
      - name: Allure report
        uses: afiore/action-allure-report@v0.1.0
        with:
          allure_results: target/allure-results
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Allure raporunu artifact olarak yükle
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/allure-report
