name: Run tests and upload allure report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Repository'yi checkout et
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. JDK ayarı
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Maven bağımlılıklarını indir ve testleri çalıştır
      - name: Run Tests
        run: mvn clean test

      # 4. Allure raporlarını oluştur
      - name: Generate Single-File Allure Report
        run: |
          allure generate --clean --single-file target/allure-results -o target/single-file-report
      

      # 5. Allure raporlarını artifact olarak yükle
      - name: Upload Single-File Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-single-report
          path: target/single-file-report/index.html
