name: Run tests and publish Allure report to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Repository'yi checkout et
      - name: Checkout code
        uses: actions/checkout@v3

      # JDK kurulumu
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Maven ile testleri çalıştır
      - name: Run tests
        run: mvn clean test

      # Geçmiş Allure raporlarını almak için gh-pages dalını checkout et
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Allure raporunu oluştur ve yükle
      - name: Publish Allure Report to GitHub Pages
        uses: simple-elf/allure-report-action@v1.11
        if: always()
        with:
          allure_results: target/allure-results   # Test sonuçlarının bulunduğu dizin
          gh_pages: gh-pages                     # GitHub Pages için branch
          allure_report: allure-report           # Allure raporunun dizini
          allure_history: allure-history         # Allure geçmiş raporları dizini
          keep_reports: 20                       # Eski raporları tutma sayısı (isteğe bağlı)

      # GitHub Pages'e yükle
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report   # Allure raporlarının bulunduğu dizin
