name: Run tests and upload Allure V2 report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Repository'yi checkout et
      - uses: actions/checkout@v3

      # Maven için JDK ayarı
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Testleri çalıştır
      - name: Run tests
        run: mvn clean test

      # Allure raporunu oluşturmak için action'ı kullan
      - name: Allure report V2
        uses: QuintilianoNery/action-allure-report-V2@0.2.0
        with:
          results-dir: target/allure-results  # Test sonuçlarının bulunduğu dizin
          report-dir: target/allure-report  # Çıktı dosyasının yolu

      # Allure raporunu artifact olarak yükle
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/allure-report  # Raporun bulunduğu dizin veya dosya
