name: Run tests and publish Allure report to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # gh-pages branch'ını ayrıca checkout et
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: mvn clean test

      # History dizinini koruma
      - name: Preserve Allure History
        run: |
          mkdir -p allure-history
          if [ -d "gh-pages/allure-history" ]; then
            cp -R gh-pages/allure-history/* allure-history/
          fi

      - name: Publish Allure Report
        uses: simple-elf/allure-report-action@v1.11
        if: always()
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report